---
title: "dataviz"
output: html_document
date: "2024-04-01"
---
```{r}
# Suppress all warnings
options(warn = -1)
```

```{r}
library(ggplot2)
library(dplyr)
# Read the data
data <- read.csv("north_america_bear_killings.csv")

head(data)
```

```{r}
# Check for null values
null_values <- sapply(data, function(x) sum(is.na(x)))
print(null_values)
```

```{r}
# Count the number of bear killings by bear type
bear_count <- data %>% 
  group_by(`Type.of.bear`) %>% 
  summarise(count = n())

print(bear_count)

# Create the bar plot
ggplot(bear_count, aes(x = `Type of bear`, y = count, fill = `Type.of.bear`)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of Bear Killings by Type of Bear",
       y = "Number of Killings") +
  theme(axis.title.x = element_blank())  # Removes x-axis label
```
```{r}
# Count the number of bear killings by year
year_count <- data %>% 
  group_by(Year) %>% 
  summarise(count = n())

print(year_count)

# Create the line plot
ggplot(year_count, aes(x = Year, y = count, group = 1)) +
  geom_line(color = "blue") +
  geom_point(color = "blue", size = 3) +
  theme_minimal() +
  labs(title = "Number of Bear Killings Over the Years",
       x = "Year",
       y = "Number of Killings") +
  annotate("text", x = 2018, y = 10, label = "")
```
```{r}
data$age <- as.character(data$age)
data$age[data$age %in% c('?', '*months', '<*')] <- NA
data <- na.omit(data)
data$age <- as.integer(data$age)

# Filter out rows where gender is not 'male' or 'female'
data <- data[data$gender %in% c('male', 'female'), ]

# Group age into bins
data$age_group <- cut(data$age, breaks = c(0, 18, 35, 55, 100), 
                      labels = c("<18", "18-35", "35-55", "55+"), include.lowest = TRUE)

# Distribution of bear attack fatalities by gender and age group
gender_age_plot <- ggplot(data[!is.na(data$age_group), ], aes(x = gender, fill = age_group)) +
  geom_bar(position = "dodge") +
  ggtitle("Distribution of Bear Attack Fatalities by Gender and Age Group") +
  xlab("Gender") +
  ylab("Number of Fatalities") +
  theme_minimal()

# Print the plot
print(gender_age_plot)

# Print quantities 
quantities <- data[!is.na(data$age_group), ] %>% 
  group_by(gender, age_group) %>% 
  summarise(count = n())

print(quantities)

```

